### ISSUE TITLE
exception in taurusmessagebox

### ISSUE THREAD

**Issue by cpascual** [piertoni/taurus#12]
To reproduce:

- launch taurusdemo
- click on dialog -> message dialog -> python tango server exception

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/taurus/qt/qtgui/dialog/taurusmessagebox.py", line 347, in py_tg_serv_exc
    traceback.print_stack(file=origin)
  File "/usr/lib/python2.7/traceback.py", line 270, in print_stack
    print_list(extract_stack(f, limit), file)
  File "/usr/lib/python2.7/traceback.py", line 23, in print_list
    '  File "%s", line %d, in %s' % (filename,lineno,name))
  File "/usr/lib/python2.7/traceback.py", line 13, in _print
    file.write(str+terminator)
TypeError: unicode argument expected, got 'str'
```

Note: the same code is also duplicated (and needs to be fixed) in `taurusmessagepanel.py`

**Comment by cpascual** [comment]
This seems to be caused by an incompatibility in StringIO. It seems it can be fixed using:

```
try:
    from StringIO import StringIO
except ImportError:
    from io import StringIO
origin = StringIO()
```
Instead of :
```
import io
origin = io.StringIO()
```

...to allow for using the old StringIO when available.


**BUT**  then one gets the following exception (also hapens in py3):

```
Traceback (most recent call last):
  File "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/dialog/taurusmessagebox.py", line 358, in py_tg_serv_exc
    msgbox = TaurusMessageBox(*sys.exc_info())
  File "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/dialog/taurusmessagebox.py", line 81, in __init__
    self, designMode)
  File "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/panel/taurusmessagepanel.py", line 271, in __init__
    self._initReportCombo()
  File "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/panel/taurusmessagepanel.py", line 284, in _initReportCombo
    report_handlers = get_report_handlers()
  File "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/panel/taurusmessagepanel.py", line 212, in get_report_handlers
    report_lib = __import__(elem, globals(), locals(), [], 0)
  File "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/panel/report/albareport.py", line 30, in <module>
    from .basicreport import SendMailDialog, SMTPReportHandler
ValueError: Attempted relative import in non-package

```

**Comment by cpascual** [comment]
This is all fixed in https://github.com/taurus-org/taurus/pull/703/commits/833ee5acfc0663608c39162496dea1562c0a137a
