### ISSUE TITLE
Exception in taurusiconcatalog on py2

### ISSUE THREAD

**Issue by cmft** [piertoni/taurus#14]
To reproduce:
```
taurusiconcatalog 
MainThread     INFO     2018-10-08 16:10:32,574 TaurusRootLogger: Using "PyQt4" for Qt
MainThread     INFO     2018-10-08 16:10:35,738 taurus.qt.qtgui.icon.icon: Setting Tango icon theme (from /home/cfalcon/tools/taurus.git/lib/taurus/qt/qtgui/icon/)
Traceback (most recent call last):
  File "/usr/local/bin/taurusiconcatalog", line 11, in <module>
    load_entry_point('taurus', 'console_scripts', 'taurusiconcatalog')()
  File "/home/cfalcon/tools/taurus.git/lib/taurus/qt/qtgui/icon/catalog.py", line 165, in main
    w = QIconCatalog()
  File "/home/cfalcon/tools/taurus.git/lib/taurus/qt/qtgui/icon/catalog.py", line 154, in __init__
    page.choiceMade.connect(self.iconSelected)
TypeError: connect() failed between GraphicalChoiceWidget.choiceMade[newstr] and iconSelected()

```

**Comment by cpascual** [comment]
Fixed in https://github.com/taurus-org/taurus/pull/703/commits/8fd1e4200ee495019edda41b57ad75c2ed591cb5
