### ISSUE TITLE
AttributeError when closing a taurusgui

### ISSUE THREAD

**Issue by cmft** [piertoni/taurus#17]
To reproduce: launch `taurusgui macrogui`.

```
MainThread     ERROR    2018-10-17 12:59:26,573 LogExceptHook: Unhandled exception:
Traceback (most recent call last):
  File "/home/cfalcon/tools/taurus.git/lib/taurus/qt/qtgui/taurusgui/taurusgui.py", line 346, in closeEvent
    TaurusMainWindow.closeEvent(self, event)
  File "/home/cfalcon/tools/taurus.git/lib/taurus/qt/qtgui/container/taurusmainwindow.py", line 822, in closeEvent
    self.saveSettings()  # save current window state before closing
  File "/home/cfalcon/tools/taurus.git/lib/taurus/qt/qtgui/container/taurusmainwindow.py", line 673, in saveSettings
    settings.setValue("TaurusConfig", Qt.QVariant(self.createQConfig()))
  File "/home/cfalcon/tools/taurus.git/lib/taurus/qt/qtcore/configuration/configuration.py", line 413, in createQConfig
    configdict = self.createConfig(allowUnpickable=False)
  File "/home/cfalcon/tools/taurus.git/lib/taurus/qt/qtgui/taurusgui/taurusgui.py", line 560, in createConfig
    cfg = TaurusMainWindow.createConfig(self, *args, **kwargs)
  File "/home/cfalcon/tools/taurus.git/lib/taurus/qt/qtcore/configuration/configuration.py", line 201, in createConfig
    itemcfgs[k] = v.createConfig(allowUnpickable=allowUnpickable)
  File "/home/cfalcon/tools/taurus.git/lib/taurus/qt/qtgui/taurusgui/taurusgui.py", line 208, in createConfig
    configdict['widget'] = self.widget().createConfig()
  File "/home/cfalcon/tools/taurus.git/lib/taurus/qt/qtcore/configuration/configuration.py", line 201, in createConfig
    itemcfgs[k] = v.createConfig(allowUnpickable=allowUnpickable)
  File "/home/cfalcon/tools/taurus.git/lib/taurus/qt/qtcore/configuration/configuration.py", line 201, in createConfig
    itemcfgs[k] = v.createConfig(allowUnpickable=allowUnpickable)
  File "/home/cfalcon/tools/taurus.git/lib/taurus/qt/qtcore/configuration/configuration.py", line 58, in createConfig
    result = getattr(self._obj, self.fget)()
AttributeError: 'NoneType' object has no attribute 'toXmlString'
```

**Comment by cmft** [comment]
Fixed
